schema_version = "1.0.0"
id = "pcb3d_importer"
version = "2.17.4"
name = "PCB 3D Importer"
tagline = "Import PCB 3D Models from KiCad"
maintainer = "30350n (Max Schlecht)"
type = "add-on"
website = "https://github.com/30350n/pcb2blender"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
blender_version_max = "5.1.0"
license = ["SPDX:GPL-3.0-or-later"]
platforms = ["windows-x64", "windows-arm64", "linux-x64", "macos-x64", "macos-arm64"]
wheels = ["./wheels/skia_python-138.0-cp311-cp311-win_arm64.whl", "./wheels/pillow-11.3.0-cp311-cp311-macosx_10_10_x86_64.whl", "./wheels/pillow-11.3.0-cp311-cp311-macosx_11_0_arm64.whl", "./wheels/skia_python-138.0-cp311-cp311-macosx_11_0_x86_64.whl", "./wheels/pillow-11.3.0-cp311-cp311-win_arm64.whl", "./wheels/skia_python-138.0-cp311-cp311-macosx_11_0_arm64.whl", "./wheels/pybind11-3.0.1-py3-none-any.whl", "./wheels/skia_python-138.0-cp311-cp311-manylinux_2_28_x86_64.whl", "./wheels/skia_python-138.0-cp311-cp311-win_amd64.whl", "./wheels/error_helper-1.4-py3-none-any.whl", "./wheels/pillow-11.3.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl", "./wheels/pillow-11.3.0-cp311-cp311-win_amd64.whl"]

[permissions]
files = "Import .pcb3d files from disk"
